const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Addidas Fit shirt',
      slug: 'addidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 12,
      brand: 'Addidas',
      rating: 4.7,
      numReviews: 13,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 50,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Addidas Fit Pant',
      slug: 'addidas-fit-panf',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 60,
      countInStock: 5,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
